# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5d773a48b79658d637cb5ef2eceb8d79d3effb22b3f8332358d01c64145cee16d1da99672bb5b7f51f79f763590a7b94c6bd080e78f696f9e6c3f2a77678670

test:
  secret_key_base: b4d8a06d35047d55e5066c8b0d7ce1a7129454bf76e4d2f0697d81875f18e7cb2b62e94cf2ecd9eb6f0a467f8233377c0447e9462bc0a4e41f9764635cdf2a1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
